// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPvywA6wYEHsW9r23KfAgfInUl5MYfOjY',
    appId: '1:237028663963:web:26e6f78354593041eadc3e',
    messagingSenderId: '237028663963',
    projectId: 'ancient--docs',
    authDomain: 'ancient--docs.firebaseapp.com',
    storageBucket: 'ancient--docs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6_dg41vrsddndJcp_uJm7DcY3CTlB96M',
    appId: '1:237028663963:android:4740e5cbdf41c44ceadc3e',
    messagingSenderId: '237028663963',
    projectId: 'ancient--docs',
    storageBucket: 'ancient--docs.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPvywA6wYEHsW9r23KfAgfInUl5MYfOjY',
    appId: '1:237028663963:web:c4139a4ee7598288eadc3e',
    messagingSenderId: '237028663963',
    projectId: 'ancient--docs',
    authDomain: 'ancient--docs.firebaseapp.com',
    storageBucket: 'ancient--docs.firebasestorage.app',
  );

}